spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
    username: auth
    password: auth

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: Md2DcKtJIOAiWmkN3+VpZH6Eyu7fyZy03KB5hHyV5n4=
  expiration: 3600000  # 1 hour
  expiration-refresh: 86400000  # 24 hours

logging:
  level:
    root: INFO
    com.ecommerce.authservice: DEBUG